apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AyaELMAFHOUM/argo-cd.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
