apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-cd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-cd
  template:
    metadata:
      labels:
        app: argo-cd
    spec:
      containers:
        - name: argo-cd
          image: aya452/argo-cd:latest  
          ports:
            - containerPort: 80
